VERSION_NUMBER_STR = '0.1a1'

MAIN_WINDOW_WIDTH = 640
MAIN_WINDOW_HEIGHT = 480

APPLICATION_TITLE = 'Virtual Space'

SIGN_IN_SCREEN_NAME = 'sign_in'
SIGN_UP_SCREEN_NAME = 'sign_up'
MENU_SCREEN_NAME = 'menu'
