"""Create product and triplet models.

Revision ID: 315eaec842dd
Revises: e788b80d09eb
Create Date: 2017-06-18 18:16:28.264901

"""
import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision = '315eaec842dd'
down_revision = 'e788b80d09eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'product',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('number', sa.Unicode(length=16), nullable=False),
        sa.Column('registry_number', sa.Unicode(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'triplet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('prefix', sa.Unicode(length=16), nullable=False),
        sa.Column('name', sa.Unicode(length=128), nullable=False),
        sa.Column('value', sa.Unicode(length=512), nullable=False),
        sa.Column('kind', sa.Unicode(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'producttriplet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('triplet_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.ForeignKeyConstraint(['triplet_id'], ['triplet.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'unit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=True),
        sa.Column('number', sa.Unicode(length=16), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'subunit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.Column('number', sa.Unicode(length=16), nullable=False),
        sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'unittriplet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.Column('triplet_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['triplet_id'], ['triplet.id'], ),
        sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'detail',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subunit_id', sa.Integer(), nullable=True),
        sa.Column('number', sa.Unicode(length=16), nullable=False),
        sa.ForeignKeyConstraint(['subunit_id'], ['subunit.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'subunittriplet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subunit_id', sa.Integer(), nullable=True),
        sa.Column('triplet_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['subunit_id'], ['subunit.id'], ),
        sa.ForeignKeyConstraint(['triplet_id'], ['triplet.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'detailtriplet',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('detail_id', sa.Integer(), nullable=True),
        sa.Column('triplet_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], ),
        sa.ForeignKeyConstraint(['triplet_id'], ['triplet.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detailtriplet')
    op.drop_table('subunittriplet')
    op.drop_table('detail')
    op.drop_table('unittriplet')
    op.drop_table('subunit')
    op.drop_table('unit')
    op.drop_table('producttriplet')
    op.drop_table('triplet')
    op.drop_table('product')
    # ### end Alembic commands ###
