"""Unique constraints for account

Revision ID: 6ad9de3d0100
Revises: 315eaec842dd
Create Date: 2017-09-18 23:58:59.580845

"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = '6ad9de3d0100'
down_revision = '315eaec842dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['email'])
    op.create_unique_constraint(None, 'account', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
